# Generated by Django 5.2.3 on 2025-07-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_slots', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.pickuphub'),
        ),
    ]
